services:
  svc:
    build:
      context: .
      target: app
    image: register-bot

  test-svc:
    build:
      context: .
      target: test
    entrypoint: make
    command: test
    working_dir: /app
    volumes:
      - .:/app
      - ${HOME}/.cache.tmp/:/tmp/.cache:rw
    environment:
      XDG_CACHE_HOME: /tmp/.cache/
      PYTEST_ADDOPTS: "-vv --junitxml=junit.xml --cov --cov-report xml:cov.xml"
