[tool.poetry]
name = "register-bot"
version = "0.0.0"
description = ""
packages = [
    { include = "src" }
]
authors = []

[tool.poetry.dependencies]
python = "^3.11"
python-telegram-bot = "^21.6"

[tool.poetry.dev-dependencies]
pre-commit = "^3"
pytest-cov = "^4.0.0"
pytest = "^7.0.0"
pytest-env = "<1"
pytest-asyncio = "<1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
line_length = 120
known_first_party = ["src", "tests"]
combine_as_imports = true
include_trailing_comma = true


[tool.black]
line-length = 120
include = '\.pyi?$'
extend-exclude = '''
/(
    tests/resources
)/
'''

[tool.coverage.run]
include = ["src/*"]

[tool.coverage.report]
include = ["src/*"]

[tool.pytest.ini_options]
junit_family = "xunit2"
asyncio_mode = "auto"
filterwarnings = [
    "error"
]
env = []

[tool.ruff]
line-length = 120
select = ["E", "F", "B", "C", "W", "B" , "B9", "UP", "ISC", "PLC", "PLE", "PLR", "PLW"]
ignore = []
fix = true
